version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_BASE_URL=https://sadhanaboard.com/api
      - VITE_SOCKET_BASE_URL=https://sadhanaboard.com
    depends_on:
      - backend
    networks:
      - saadhanaboard-network

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    environment:
      - DB_HOST=database
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=saadhanaboard
      - DB_PORT=5432
      - JWT_SECRET=saadhanaboard_production_secret_key_2025
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=saadhanaboard_secure_admin_password_2025
      - ADMIN_EMAIL=admin@sadhanaboard.com
      - CORS_ORIGIN=https://sadhanaboard.com,https://www.sadhanaboard.com
      - NODE_ENV=production
    depends_on:
      - database
    networks:
      - saadhanaboard-network

  # Database service
  database:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=saadhanaboard
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - saadhanaboard-network

volumes:
  postgres_data:

networks:
  saadhanaboard-network:
    driver: bridge